### PR TITLE
Use background color from theme for separator line

### PR DESCRIPTION
**Pull request by eckende**

### CODE REVIEW

**Comment by elliotwaite** [comment]
Thanks for this contribution! You're the first person to contribute to this project.

I've submitted the updated version (v1.0.0) to Chrome and Firefox for review. It should be made available within the next 24 hours unless there are some abnormal delays.

**Comment by eckende** [comment]
You're welcome, Elliot! Thanks for the quick submission! I discovered your webextension earlier today and noticed this line being white. I figured this was the best way to fix it and it seems it really is :)

**Comment by elliotwaite** [comment]
Yep, that was an elegant solution.

**Comment by eckende** [comment]
Well, this was only my second pull request ever so I was thinking more about submitting a pull request vs achieving the line color change through other methods but thank you ;)

**Pull request merged**
