### PR TITLE
Add video percentage for homepage

### PR DESCRIPTION
**Pull request by xethlyx**
It's 3am and I haven't tested this extensively. This will also bring this extension closer to solving #26. If I have time tomorrow I'll try to get it to work with other pages

### CODE REVIEW

**Comment by elliotwaite** [comment]
@xethlyx, thanks for the contribution! I'll merge it and start testing it out. I might make a few small changes, but it looks pretty good. If you want to add any additional changes tomorrow or whenever you get the chance, just open up another pull request. Also, I'll check in with you to make sure it's working as you intended before publishing the update to the Chrome Web Store and the other platforms.

**Comment by elliotwaite** [comment]
I just add the following changes: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/commit/899a89a066ec25a204f5f882184a1fa7ccb9c377

It now shows the text percentage as color-coded (between green and red depending on the rating). Let me know what you think.

**Comment by xethlyx** [comment]
Yup, it's working as intended and your changes look awesome.

**Comment by elliotwaite** [comment]
Okay, the update has been published (version 1.1.0). Thanks again for the contribution.

**Pull request merged**
